//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonimowaAnkieta
{
    using System;
    using System.Collections.Generic;
    
    public partial class scale_numbers
    {
        public int id_number { get; set; }
        public int number { get; set; }
    }
}
